name: RSPassword
main: com.dkabot.RSPassword.RSPassword
version: 0.5
author: dkabot
database: true
description: Password protected signs that toggle redstone.
commands:
  rsp:
    description: Readies a password for use on a sign.
    usage: /<command> <password> then right click on the sign you wish to use a password on.
